version: "3.8"

services:
  db_postgres:
    image: postgres:15-alpine
    container_name: meu_projeto_db
    restart: always
    environment:
      - POSTGRES_USER=${PGUSER:-postgres}
      - POSTGRES_PASSWORD=${PGPASSWORD:-K33ps@f&}
      - POSTGRES_DB=${PGDATABASE:-expense_management}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - rede_projeto
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${PGUSER:-postgres} -d ${PGDATABASE:-expense_management}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  # --- BACK-END (FLASK) ---
  backend:
    build: ./back
    container_name: meu_projeto_backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - PGUSER=${PGUSER:-postgres}
      - PGPASSWORD=${PGPASSWORD:-postgres}
      - PGHOST=db_postgres
      - PGPORT=5432
      - PGDATABASE=${PGDATABASE:-expense_management}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-chave_super_secreta_padrao}
      - FLASK_DEBUG=False
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS:-*}
    depends_on:
      db_postgres:
        condition: service_healthy
    networks:
      - rede_projeto

  # --- FRONT-END (REACT) ---
  frontend:
    build: ./front
    container_name: meu_projeto_frontend
    restart: always
    ports:
      - "3050:80"
    depends_on:
      - backend
    networks:
      - rede_projeto

volumes:
  postgres_data:

networks:
  rede_projeto:
    driver: bridge
