version: "3.8"

services:
  db_postgres:
    image: postgres:15-alpine
    container_name: meu_projeto_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=K33ps@f&
      - POSTGRES_DB=expense_management
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - rede_projeto

  # --- BACK-END (FLASK) ---
  backend:
    build: ./back
    container_name: meu_projeto_backend
    restart: always
    ports:
      - "5050:5000"
    environment:
      - PGUSER=postgres
      - PGPASSWORD=K33ps@f&
      - PGHOST=db_postgres
      - PGPORT=5432
      - PGDATABASE=expense_management
      - JWT_SECRET_KEY=b09e38f40ed87d5efd31a03ce3d150205063d48030040637dddbb80403286426
      - FLASK_DEBUG=False
      - CORS_ALLOWED_ORIGINS=http://localhost:3000
    depends_on:
      - db_postgres
    networks:
      - rede_projeto

  # --- FRONT-END (REACT / TS) ---
  frontend:
    build: ./front
    container_name: meu_projeto_frontend
    restart: always
    ports:
      - "3050:80"
    depends_on:
      - backend
    networks:
      - rede_projeto

volumes:
  postgres_data:

networks:
  rede_projeto:
    driver: bridge
